#!/bin/bash
RECURSE=0
if [[ $1 == '-r' ]]; then
    shift
    RECURSE=1
fi
URL=${1?Usage: $0 [-r] <URL>}
read URL RETCODE TTTL NEWURL < <(curl -o /dev/null --silent --head --write-out "$URL %{http_code} %{time_total} %{redirect_url}\n" "$URL")
echo $URL $RETCODE $TTTL $NEWURL
if [[ $RECURSE == 1 && ( $RETCODE == '301' || $RETCODE == '302' ) ]]; then
    $0 -r $NEWURL
fi
