#!/bin/bash

perl -MSocket -plane '
	BEGIN {
		%CACHE=();
		sub gethost {
			$ip = $1;
			unless (defined $CACHE{$ip}) {
				@name = gethostbyaddr(inet_aton($ip),AF_INET);
				$CACHE{$ip} = $name[0] ? $name[0] : $ip;
			}
			return $CACHE{$ip};
		}
	}
	s/\b(([0-9]{1,3}\.){3}([0-9]{1,3}))\b/$1." ".gethost($1)/eg;
'
