#!/bin/bash

perl -MSocket -plane '
	BEGIN {
		%CACHE=();
		sub gethost {
			$ip = join( ".", unpack "C4", pack "N", $1);
			unless (defined $CACHE{$ip}) {
				@name = gethostbyaddr(inet_aton($1),AF_INET);
				$CACHE{$ip} = $name[0] ? $name[0] : $1;
			}
			return $CACHE{$ip};
		}
	}
	s/\b(([0-9]{1,3}\.){3}([0-9]{1,3}))\b/gethost($1)/eg;
'
