#!/bin/bash

perl -MSocket -plane '
	BEGIN {
		%CACHE=();
		sub gethost {
			$ip = join( ".", unpack "C4", pack "N", $1);
			$CACHE{$ip} = gethostbyaddr(inet_aton($1),AF_INET) unless defined $CACHE{$ip};
			return $CACHE{$ip};
		}
	}
	s/\b(([0-9]{1,3}\.){3}([0-9]{1,3}))\b/gethost($1)/eg;
'
