#!/bin/bash
if (( $# )); then
  perl -lane "$*"
else
  echo "# Usage: $0 'print @F[0]'"
  echo -e "# Reading standard input to show column numbers ...\n"
  head -1 | perl -plane 'print map{$i++=>"\t$_\n"}@F'
fi
