#!/bin/bash
echo "# Columns are delimited by white space if no parameter is passed."
echo "# Reading standard input to show column numbers ..."
head -1 | perl -F/$1/ -lane 'print map{$i++=>"\t$_\n"}@F; print "# Actual line read:"; print;'
