#!/bin/bash
echo "# Columns are delimited by white space if no parameter is passed."
echo "# Reading standard input to show column numbers ..."
CLI=""
if (( $# )); then
    CLI="-F/$1/"
fi
head -1 | perl $CLI -lane 'print map{$i++=>"\t$_\n"}@F; print "# Actual line read:"; print;'
