#!/usr/bin/perl

while (<>) {
    if (/^(\w+)(\*|\!)?\s/) {
        $header = $_;
        $queue_id = $1;
        $_ = <>;
        chop;
        $msg = $_;

        if (/^\(.*(\d{3}) (\d.\d.\d) .*\)$/) {
            $reply = $1;
            $error = $2;

            $_ = <>;
            chop;
            s/\s+//g;
            $email = $_;

            print "$queue_id $reply $error $email $msg\n";
        } elsif ($header =~ /MAILER-DAEMON/) {
            print "$queue_id -- MAILER-DAEMON\n";
        } else {
            print "$queue_id -- PARSE-ERROR\n";
        }
    }
}
